---

- name: Create or delete ec2 instances, deploy k8s to them
  hosts: localhost
  collections:
    - amazon.aws
    - community.aws.ec2_instance_facts

  vars:
    ansible_aws_instance_type: "t2.micro"
    ansible_aws_image_name:  "ami-02f147dfb8be58a10"
    ansible_aws_region: "us-west-2"
    ansible_aws_security_group: "rke_k8s_subnet-43cd7908"
    ansible_aws_key_name: "alklein_us-west"
    ansible_aws_instance_group: "rke-k8s"
    ansible_aws_vpc_subnet_id: "subnet-43cd7908"
    ansible_instance_status: terminated

    ansible_ec2_debug: false

  roles:
  - role: ansible-role-ec2-instances
    vars:
    ansible_instance_count: 7
