---

- name: Create or delete ec2 instances, deploy k8s to them
  hosts: localhost
  collections:
    - amazon.aws
    - community.aws.ec2_instance_facts

  vars:
    ansible_aws_instance_type: "t2.micro"
    ansible_aws_image_name:  "ami-01fee56b22f308154"
    ansible_aws_region: "us-west-2"
    ansible_aws_security_group: "Filbert_Estates_ssh"
    ansible_aws_key_name: "alklein_us-west"
    ansible_aws_instance_group: "test"
    ansible_instance_status: create
    ansible_aws_activity: build
    ansible_ec2_debug: false
    ansible_ec2_packages:
      - docker-ce

  roles:
  - role: ansible-role-ec2-instances
    hosts: localhost
    vars:
    ansible_instance_count: 1
    when: ansible_aws_activity == "build"

  - role: ansible-role-k8s-on-ec2
    hosts: tag_group_k8s_rke
    when: ansible_aws_activity == install

