---

# Start or stop EC2 instances

- name: Start or stop EC2 instances
  amazon.aws.ec2:
    state: '{{ ansible_instance_status }}'
    instance_ids: '{{ item.instance_id }}'
    region: "{{ ansible_aws_region }}"
  with_items:
    - "{{ ec2.instances }}"