---

# Install specified packages on EC2 instances

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
    use_backend: yum
  loop: "{{ ansible_ec2_packages }}"
  remote_user: ec2-user
  become: true
